### ISSUE TITLE
I cannot cancel or remove uploads

### ISSUE THREAD

**Issue by wisark** [slskd/slskd#1274]
Hi, when I try to use the "Cancel All" option from the Uploads menu I always get the error showed in the first image "Cannot read properties of undefined (reading 'status')" just like the user in issue [#1226](https://github.com/slskd/slskd/issues/1226) and after a while slskd freezes and it shows a message saying it lost connection. When I try to use the "Remove All" option, I get a different type of error, as seen in the second image. The result in both cases is the same, I cannot remove the list of uploads and therefore it grows and is already unsustainable. Only from System > Data > "Clear all completed uploads" I manage to remove the completed uploads in certain cases (not always), but in any case the uploads with the status "Queued, Local" or "Completed, Cancelled" continue to accumulate and I can't find a way to remove them. Is there a way to solve this? Thanks a lot in advance! 

![CANCELL ALL](https://github.com/user-attachments/assets/defcc669-51f5-4278-8618-74da9e7f6b14)
![remove all completed](https://github.com/user-attachments/assets/757c872b-d02b-4086-859a-f7776a885ecd)

**Comment by jpdillingham** [comment]
The method that clears transfers from this screen is inefficient and can fail like this on low-spec (or even high-spec systems with a lot of  transfers).  If the button isn't working for you, try using the buttons in the System menu:

![image](https://github.com/user-attachments/assets/31f1b4e9-5e4e-4bd7-8e57-9839328b6fb9)

It might make sense to set retention settings for uploads so that they clear themselves on a regular basis.  You can read about that here: https://github.com/slskd/slskd/blob/master/docs/config.md#data-retention

**Comment by jpdillingham** [comment]
Fixed in 0.24.0

**Comment by fnool** [comment]
I'm still experiencing this on 0.24.5.0 - neither the "cancel" button in the upload page nor the "clear all completed uploads" button in options will remove "queued, locally" transfers

**Comment by jpdillingham** [comment]
@fnool can you provide more info? Is this happening frequently?

The logic has been carefully rewritten in recent versions so that "stuck" transfers are only possible if the application crashes during the enqueue process.  I doubt cancellation works for these scenarios because `Queued, Locally` is a transient state that should exist only between the time the transfer is requested and either the remote client responds or a timeout is reached.

~~I can adjust the logic that cleans up "hanging" transfers at startup to make sure it cleans these up, if it isn't already.~~ I confirmed that any transfer record that doesn't include the `Completed` flag at startup will be set to `Completed, Errored`, so I would need to know how often this is happening and see some application logs to see how to prevent it.

**Comment by fnool** [comment]
Only started using slskd yesterday and encountered this for the first and so far only time after a few dozen successful uploads. With this person the whole album failed except for this one song, which is now stuck.

Where can I find the logs you need?

![Image](https://github.com/user-attachments/assets/0af75e3c-7e7a-45ee-a5e3-6dad344f02ca)

**Comment by fnool** [comment]
Following a restart, those stuck entries showed as "completed, errored" and I was able to manually remove them.
