### ISSUE TITLE
Failed to scan share

### ISSUE THREAD

**Issue by BachoSeven** [slskd/slskd#155]
I noticed two issues with scanning my share when running `slsk` for the first time:

- this warning, although I defined `-v ~/slsk/shared:/var/slskd/shared`:
``` sh
[15:43:34 WRN] Failed to scan share /.local/share/slskd/shared: Could not find a part of the path '/.local/share/slskd/shared'.
```

- however doing `docker exec -it slskd sh` and then going into `/var/slskd/shared` I can see the shared directory with the correct name, but cannot see its contents or `cd` into it... Furthermore, from the logs I can see that if it did scan it, it failed to do so because it says `Found 1 directories and 1 files`, while the shared directory is very big... The point though is that my `~/slsk/shared` is a symlink to another disk; is that allowed?

Edit: if it's helpful, I launched docker with `-u $(id -u):$(id -g)`

P.S. Also, there's a discrepancy between the README where it says to use `/var/lib/incoming` and the Dockerfile where it's `/var/lib/incomplete`.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  You're seeing the warning because there's an implicit share that is always pointed to `/.local/share/slskd/shared`, and I removed the code that created this directory.  It isn't affecting functionality, but I will need to put that back in to fix this.

Thanks for the heads up on the documentation also.

**Comment by BachoSeven** [comment]
How about the symlink? Should it be working? I haven't been able to verify if my files are visible from another computer but I think it's not, either because it's a symlink or maybe because it's on another disk; shouldn't be a permissions problem since I'm running everything as my user and the user owns the shared files on the disk

**Comment by tandy-1000** [comment]
I'm not sure if #154 is a separate bug from this.

**Comment by BachoSeven** [comment]
@jpdillingham I just tried 0.13.1 and I'm getting this: 
```
[12:45:53 ERR] Filesystem exception: Directory /.local/share/slskd/shared does not exist, and could not be created: Access to the path '/.local/share/slskd/shared' is denied.
System.IO.IOException: Directory /.local/share/slskd/shared does not exist, and could not be created: Access to the path '/.local/share/slskd/shared' is denied.
 ---> System.UnauthorizedAccessException: Access to the path '/.local/share/slskd/shared' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at slskd.Program.VerifyDirectory(String directory, Boolean createIfMissing, Boolean verifyWriteable)
   --- End of inner exception stack trace ---
   at slskd.Program.VerifyDirectory(String directory, Boolean createIfMissing, Boolean verifyWriteable)
   at slskd.Program.Main(String[] args)
[12:45:54 ERR] Filesystem exception: Directory /.local/share/slskd/shared does not exist, and could not be created: Access to the path '/.local/share/slskd/shared' is denied.
System.IO.IOException: Directory /.local/share/slskd/shared does not exist, and could not be created: Access to the path '/.local/share/slskd/shared' is denied.
 ---> System.UnauthorizedAccessException: Access to the path '/.local/share/slskd/shared' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at slskd.Program.VerifyDirectory(String directory, Boolean createIfMissing, Boolean verifyWriteable)
   --- End of inner exception stack trace ---
   at slskd.Program.VerifyDirectory(String directory, Boolean createIfMissing, Boolean verifyWriteable)
   at slskd.Program.Main(String[] args)
[12:45:55 ERR] Filesystem exception: Directory /.local/share/slskd/shared does not exist, and could not be created: Access to the path '/.local/share/slskd/shared' is denied.
System.IO.IOException: Directory /.local/share/slskd/shared does not exist, and could not be created: Access to the path '/.local/share/slskd/shared' is denied.
 ---> System.UnauthorizedAccessException: Access to the path '/.local/share/slskd/shared' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at slskd.Program.VerifyDirectory(String directory, Boolean createIfMissing, Boolean verifyWriteable)
   --- End of inner exception stack trace ---
   at slskd.Program.VerifyDirectory(String directory, Boolean createIfMissing, Boolean verifyWriteable)

```

**Comment by jpdillingham** [comment]
I'm just going to have to take the default share out of the config.  I'll push a new image shortly.

**Comment by jpdillingham** [comment]
Should be fixed in 0.13.2, please give it a shot and let me know!

**Comment by BachoSeven** [comment]
Yea the default shares errors are gone :)

However I still think the symlink is not resolved(if you want to check my shares since I'm not able to from the same connection, username is `Bacho`)

Also, I noticed this new error message in 0.13.2(seems unrelated):

```
[23:01:40 ERR] Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] 
CREATE TABLE "Searches" ( 
    "Id" TEXT NOT NULL CONSTRAINT "PK_Searches" PRIMARY KEY, 
    "EndedAt" TEXT NULL, 
    "FileCount" INTEGER NOT NULL, 
    "LockedFileCount" INTEGER NOT NULL, 
    "ResponseCount" INTEGER NOT NULL, 
    "ResponsesJson" TEXT NULL, 
    "SearchText" TEXT NULL, 
    "StartedAt" TEXT NOT NULL, 
    "State" INTEGER NOT NULL, 
    "Token" INTEGER NOT NULL 
); 
[23:01:40 ERR] HTTP GET /api/v0/searches/c62d5fa8-28ab-440c-8994-74b2ab280f26/responses responded 500 in 1077.5501 ms 
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Searches" already exists'. 
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) 
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext() 
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext() 
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult() 
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) 
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader() 
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery() 
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject) 
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) 
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection) 
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables() 
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated() 
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated() 
   at lambda_method41(Closure , IServiceProvider , DbContextOptions`1 ) 
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext() 
   at slskd.Search.SearchService.FindAsync(Expression`1 expression, Boolean includeResponses) 
   at slskd.Search.API.SearchesController.GetResponsesById(Guid id) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() 
--- End of stack trace from previous location --- 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() 
--- End of stack trace from previous location --- 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) 
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) 
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) 
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) 
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) 
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext) 
[23:01:40 ERR] Connection id "0HMB3CJBGJPPP", Request id "0HMB3CJBGJPPP:0000000A": An unhandled exception was thrown by the application. 
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Searches" already exists'. 
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) 
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext() 
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext() 
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult() 
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) 
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader() 
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery() 
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject) 
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) 
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection) 
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables() 
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated() 
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated() 
   at lambda_method41(Closure , IServiceProvider , DbContextOptions`1 ) 
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext() 
   at slskd.Search.SearchService.FindAsync(Expression`1 expression, Boolean includeResponses) 
   at slskd.Search.API.SearchesController.GetResponsesById(Guid id) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() 
--- End of stack trace from previous location --- 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() 
--- End of stack trace from previous location --- 
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) 
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) 
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) 
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) 
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) 
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext) 
   at slskd.Startup.<>c.<<Configure>b__20_0>d.MoveNext() 
--- End of stack trace from previous location --- 
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)  
```

**Comment by jpdillingham** [comment]
That's a transient error that I thought was extremely rare, but it seems maybe not.  It isn't a big deal, and it corrects itself, but I'll create a separate issue to figure out how to suppress it.

Regarding the symlink, I haven't tried it so I'll need to do some investigation and get back to you.  Off the top of my head I can't think of a reason it wouldn't work.

**Comment by BachoSeven** [comment]
Thanks. btw I noticed a warning regarding shares browsing, I don't think it's opening an issue so I'll post it here for now:
```
[11:53:53 WRN] Failed to resolve browse response: startIndex cannot be larger than length of string. (Parameter 'startIndex')
```

**Comment by jpdillingham** [comment]
Can you share your configuration?

**Comment by BachoSeven** [comment]
It's the same as I wrote in https://github.com/slskd/slskd/issues/155#issuecomment-901886098 except for `--restart` which I onw set to `unless-stopped` but that's irrelevant

**Comment by jpdillingham** [comment]
Regarding the warning about the distributed message, that's a malformed message from someone else on the network and can safely be ignored.

All the transfer and chat data is tracked by the backend, the web frontend just reads it.  So no, it doesn't have to be open to capture.

I'll be looking at the browse issue later tonight.  Are there any files in that directory?

**Comment by jpdillingham** [comment]
Confirmed an issue with aliasing and browse results on non-Windows platforms.  I've created #162 to track this directly.

Both remaining bugs mentioned in this issue now have dedicated issues, so I'll close this to make it easier to track updates.

**Comment by BachoSeven** [comment]
@jpdillingham I've now verified on the latest release that the symlink is not resolved (confimed by browsing from another client). My shared folder contains a symlink to a location outside of it, is that not supposed to work?

**Comment by jpdillingham** [comment]
@BachoSeven I created issue #320 to take a look at this specific issue.  I expected symlinks to be completely transparent, but that may not actually be the case.

**Comment by Dam-Buty** [comment]
@BachoSeven I would imagine you solved your issue in the meantime but because this issue ranks high in the Google results i'll post my workaround.

Basically i was able to avoid this issue by adding a few volumes in the docker-compose, such as :  

```
    volumes:
      - /data/slskd:/app
      - /data/music:/shares/music
      - /data/video:/shares/videos
```

And then sharing them from the `slskd.yml`.

**Comment by BachoSeven** [comment]
@Dam-Buty I had solved the original issue if you look above, apart from the `symlink` problem (I think, I'll have to check if it's changed), which is still tracked in #320.
